### ISSUE TITLE
fix year cutpoints

### ISSUE THREAD

**Issue by galileukim** [worldbank/institutional-assessment-dashboard#190] opened 2023-09-19 15:35 UTC
for static ctf: 2018+ data.
for dynamic ctf: 2013+ data.

**Comment by kannanv93** [comment] 2023-09-26 03:14
closed as duplicate of [https://github.com/worldbank/institutional-assessment-dashboard/issues/196](url)

**Closed by kannanv93** 2023-09-26 03:14 UTC
