### ISSUE TITLE
ETL fixes from first round of feedback on CLIAR 2.0

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#216] opened 2023-10-23 21:02 UTC
Based on the first round of team comments on the CLIAR 2.0 database, we have the following coding fixes and data edits:

CODE TO EDIT
- [x] Corruption family => rename to “Absence of Corruption” (Already renamed in DEV and adjusted text in Dashboard. Not sure where else would be needed to make changes?)
- [x] Remove non-WB member countries: Cuba + Korea, Dem. People's Rep.  
- [x] The variables wdi_seprmenrltczs  and wdi_sesecenrltczs (these are the student/teacher ratios) should be flipped. A higher number is worse than a lower one – having lots of students per teacher is bad for learning. (Noted as to invert in the metadata_dev (column t). Propose process: X * -1)
- [x] The variable wb_gfdb_oi_01 (bank concentration) should also be flipped. This variable measures “Assets of three largest commercial banks as a share of total commercial banking assets.” So a higher number means more concentration, less competition which is bad. (Noted as to invert in the metadata_dev (column t). Proposed process: 100 - X)
- [ ] The variable political polarization (vdem_core_v2cacamps) should also be flipped. (Noted as to invert in the metadata_dev (column t). Proposed process: X * -1)
- [x] Double check that vdem_core_v2x_corr is indeed inverted. (We have revised this several times, but because it was raised, let us double check.)

-> @galileukim: can you lead the inversion, data dropping, and going from DEV to db_variables? @arpaterson42 can support as you see fit

ALSO NOTE THE FOLLOWING DATA DECISIONS (_with changes already reflected in the DEV metadata_)
DATA DECISIONS
1.	We decided to Keep debt transparency
2.	We decided to not benchmark the romelli_cbi_central_bank_indepen varibale
3.	We decided to compute the PFM family (global) average in the static version as a conservative estimate (i.e., only for countries with all the indicators).
4.	We decided to not benchmark wdi_shmedbedszs (G=26): Hospital beds (per 1,000 people)
5.	We decided to keep wdi_shstaanvczs (G=69): Pregnant women receiving prenatal care (%) (no changes).

**Comment by galileukim** [comment] 2023-10-24 18:18
@erwbg please note that regarding point 3, the pupil-teacher-ratio does not have a clear maximum. I'm flipping it with the empirical maximum instead of the 1-x methodology proposed.

**Comment by galileukim** [comment] 2023-10-24 18:43
I like that. Let's do it that way. Another issue I have observed was that the V-DEM's polarization is not 0-4 as stated in the description, but from the IRT.

**Comment by galileukim** [comment] 2023-10-24 18:51
That would be great. Not for now, but something to keep in mind when we share the codebook.

All the best,
Galileu

**Comment by galileukim** [comment] 2023-10-24 18:55
@erwbg @kannanv93 this issue is now closed. all of the improvements have been addressed in our CLIAR_UAT_family_avg branch. @kannanv93 please note that you will need to re-download the updated db_variables file to work as intended. All of our up-to-date data is in our OneDrive, in the ` data\cliar_data\data\input\cliar` folder.

**Closed by galileukim** 2023-10-24 18:55 UTC
Labels: enhancement, high priority
